/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IdeanButton {
        "type": 'primary'|'secundary'|'text'| 'disabled';
    }
    interface IdeanCard {
    }
    interface IdeanTextInput {
    }
}
declare global {
    interface HTMLIdeanButtonElement extends Components.IdeanButton, HTMLStencilElement {
    }
    var HTMLIdeanButtonElement: {
        prototype: HTMLIdeanButtonElement;
        new (): HTMLIdeanButtonElement;
    };
    interface HTMLIdeanCardElement extends Components.IdeanCard, HTMLStencilElement {
    }
    var HTMLIdeanCardElement: {
        prototype: HTMLIdeanCardElement;
        new (): HTMLIdeanCardElement;
    };
    interface HTMLIdeanTextInputElement extends Components.IdeanTextInput, HTMLStencilElement {
    }
    var HTMLIdeanTextInputElement: {
        prototype: HTMLIdeanTextInputElement;
        new (): HTMLIdeanTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "idean-button": HTMLIdeanButtonElement;
        "idean-card": HTMLIdeanCardElement;
        "idean-text-input": HTMLIdeanTextInputElement;
    }
}
declare namespace LocalJSX {
    interface IdeanButton {
        "type"?: 'primary'|'secundary'|'text'| 'disabled';
    }
    interface IdeanCard {
    }
    interface IdeanTextInput {
    }
    interface IntrinsicElements {
        "idean-button": IdeanButton;
        "idean-card": IdeanCard;
        "idean-text-input": IdeanTextInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "idean-button": LocalJSX.IdeanButton & JSXBase.HTMLAttributes<HTMLIdeanButtonElement>;
            "idean-card": LocalJSX.IdeanCard & JSXBase.HTMLAttributes<HTMLIdeanCardElement>;
            "idean-text-input": LocalJSX.IdeanTextInput & JSXBase.HTMLAttributes<HTMLIdeanTextInputElement>;
        }
    }
}
